# Generated by Django 6.0.4 on 2026-07-27 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_brand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-created_at"], name="prod_created_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "-created_at"], name="prod_cat_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["seller", "-created_at"], name="prod_seller_idx"
            ),
        ),
    ]
